#13 Sprint 13
valer0n3/java-shareit pull request #1
Opened 2023-01-18 20:59 UTC by valer0n3

2023-01-19 10:23 UTC, AnastasiyaFomkina requested changes
Отличная работа - молодец 👍 Оставила комментарий для саморазвития, можно сделать, если будет время и желание

2023-01-19 10:23 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> + * TODO Sprint add-controllers.
В коммерческой разработке, когда код из `TODO` реализован, принято его удалять, чтобы он не путал других разработчиков.
Удали, пожалуйста, все `TODO`, которые были выполнены во всем проекте

2023-01-19 10:23 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    public Exception incorrectValue(final IncorrectInputException e) {
Лучше указывать полное название для переменных, а не сокращать из до одной буквы

2023-01-19 10:23 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        log.warn("Error 400: " + e.getMessage());
При логировании параметров, лучше использовать заполнитель(placeholder) `{}`, а не конкатенацию. 
Тогда код будет выглядить более лаконично:

```suggestion
        log.warn("Error 400: {}", e.getMessage());
```

2023-01-19 10:23 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/exception/Exception.java
> +    public Exception(String error, String description) {
Можно сгененировать с помощью lombok: `@AllArgsConstructor`

2023-01-19 10:23 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +                                   @RequestHeader("X-Sharer-User-Id") int userId,
Лучше вынести повторяющийся хэдер в константу

2023-01-19 10:23 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    // private int owner;
Нужно удалить весь закомментированный код

2023-01-19 10:23 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/dto/mapper/ItemMapper.java
> +    public static ItemDto mapItemToItemDto(Item item) {
_Саморазвитие_
В коммерческой разработке принято максимально избавляться от шаблонного кода, чтобы не перегружать и так большие и объемные проекты. Для маппинга сущностей часто используется библиотека [Mapstruct](https://blog.skillfactory.ru/glossary/mapstruct/), которая позволяет автоматически настраивать маппинг из одной сущности в другую с помощью описания интерфейсов и аннотаций.
Вот [здесь](https://www.baeldung.com/mapstruct) есть отличный гайд для старта работы с библиотекой. 
При наличии свободного времени можно поизучать и попробовать прикрутить в проект

2023-01-19 10:23 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImplementation.java
> +public class ItemServiceImplementation implements ItemService {
🔥

2023-01-19 10:23 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/storage/UserStorageInMemoryImpl.java
> +    private Map<Integer, User> userHashMap = new HashMap<>();
Может быть `final`

2023-01-19 11:49 UTC, valer0n3 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> + * TODO Sprint add-controllers.
Исправлено.

2023-01-19 11:50 UTC, valer0n3 commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    public Exception incorrectValue(final IncorrectInputException e) {
Исправлено

2023-01-19 11:52 UTC, valer0n3 commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        log.warn("Error 400: " + e.getMessage());
Исправлено.

2023-01-19 11:55 UTC, valer0n3 commented on src/main/java/ru/practicum/shareit/exception/Exception.java
> +    public Exception(String error, String description) {
Исправлено.

2023-01-19 12:00 UTC, valer0n3 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +                                   @RequestHeader("X-Sharer-User-Id") int userId,
Исправлено.

2023-01-19 12:01 UTC, valer0n3 commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    // private int owner;
Исправлено.

2023-01-19 12:02 UTC, valer0n3 commented on src/main/java/ru/practicum/shareit/user/storage/UserStorageInMemoryImpl.java
> +    private Map<Integer, User> userHashMap = new HashMap<>();
Исправлено.

2023-01-19 14:44 UTC, valer0n3 commented on src/main/java/ru/practicum/shareit/item/dto/mapper/ItemMapper.java
> +    public static ItemDto mapItemToItemDto(Item item) {
При добавлении

2023-01-19 14:48 UTC, valer0n3 commented on src/main/java/ru/practicum/shareit/item/dto/mapper/ItemMapper.java
> +    public static ItemDto mapItemToItemDto(Item item) {
При добавления в pom плагина (как указано в статье https://www.baeldung.com/mapstruct) появляется множество ошибок: cannot find symbol 
Пока не разобрался как это пофиксить. 
![image](https://user-images.githubusercontent.com/25436468/213472959-6138af7b-fdbd-4e78-9017-04ef35ceb7fe.png)


<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.5.1</version>
    <configuration>
        <source>1.8</source>
        <target>1.8</target>
        <annotationProcessorPaths>
            <path>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct-processor</artifactId>
                <version>1.5.3.Final</version>
            </path>
        </annotationProcessorPaths>
    </configuration>
</plugin>

2023-01-20 08:27 UTC, valer0n3 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImplementation.java
> +public class ItemServiceImplementation implements ItemService {
Переделал.

2023-01-20 12:55 UTC, AnastasiyaFomkina approved these changes

2023-01-20 12:57 UTC, merged