#14 Sprint 14
valer0n3/java-shareit pull request #2
Opened 2023-02-04 23:19 UTC by valer0n3

2023-02-05 13:35 UTC, AnastasiyaFomkina requested changes
Задание со звездочкой: 
Лучше стараться максимально декомпозировать большие методы на более мелкие логические составляющие, так код будет проще читать и тестировать в дальнейшем.
Предлагаю выделить общие части в сервисах и вынесли их в приватные методы. Вообще есть отличный ресурс, где можно почитать про рефакторинг кода и взять на заметку подходы по декомпозиции - [рефакторинг гуру](https://refactoring.guru/) (может не открываться без впн)

2023-02-05 13:35 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/enums/BookingStatusEnum.java
> +    transferStateToEnum(String stateInput) {
Лучше использовать встроенный метод [valueOf](https://linuxhint.com/use-valueof-method-of-enum-java-class/). Он принимает на вход строку с названием и подбирает соответствующее значение перечисления. Если такого значения не нашлось - выбрасывает `IllegalArgumentException` или `NullPointerException`, если значение == null

2023-02-05 13:35 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/dto/NewBookingDto.java
> +    private LocalDateTime start;
Может быть только [@FutureOrPresent](https://www.baeldung.com/javax-validation#:~:text=%40Future%20and%20%40FutureOrPresent)

2023-02-05 13:35 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/dto/NewBookingDto.java
> +    private LocalDateTime end;
Может быть только [@Future](https://www.baeldung.com/javax-validation#:~:text=in%20Java%208.-,%40Future,-and%20%40FutureOrPresent%20validate)

2023-02-05 13:35 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImplementation.java
> +        if (newBookingDto.getEnd().isBefore(LocalDateTime.now()) ||
Можно провалидировать с помощью аннотаций

2023-02-05 13:35 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImplementation.java
>      private final ItemStrorage itemStorage;
Нигде больше не используется, нужно удалить

2023-02-05 13:35 UTC, AnastasiyaFomkina commented on src/main/resources/application.properties
> +#spring.datasource.driverClassName=org.postgresql.Driver
Нужно вернуть настройки для работы с postgresql, а старые удалить

2023-02-05 13:35 UTC, AnastasiyaFomkina commented on src/main/resources/TableCreateForPostgres.txt
> +CREATE TABLE IF NOT EXISTS users
Лучше удалить данный файл, так как есть скрипт для инициализации базы ниже

2023-02-05 13:35 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImplementation.java
> +                .stream().map(commentMapper::mapCommentToCommentDto).collect(Collectors.toList());
Лучше бить методы стрима по строкам для лучшей читаемости:
```suggestion
                .stream()
                .map(commentMapper::mapCommentToCommentDto)
                .collect(Collectors.toList());
```

2023-02-06 09:28 UTC, valer0n3 commented on src/main/java/ru/practicum/shareit/booking/enums/BookingStatusEnum.java
> +    transferStateToEnum(String stateInput) {
Переделал. Очень полезный метод, спасибо:)

2023-02-06 09:32 UTC, valer0n3 commented on src/main/java/ru/practicum/shareit/booking/dto/NewBookingDto.java
> +    private LocalDateTime start;
Добавил аннотацию.

2023-02-06 09:32 UTC, valer0n3 commented on src/main/java/ru/practicum/shareit/booking/dto/NewBookingDto.java
> +    private LocalDateTime end;
Добавил аннотацию.

2023-02-06 09:50 UTC, valer0n3 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImplementation.java
> +        if (newBookingDto.getEnd().isBefore(LocalDateTime.now()) ||
Убрал ненужные проверки, после добавления аннотаций @Future

2023-02-06 09:53 UTC, valer0n3 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImplementation.java
>      private final ItemStrorage itemStorage;
Неиспользуемая переменная класса удалена.

2023-02-06 09:55 UTC, valer0n3 commented on src/main/resources/application.properties
> +#spring.datasource.driverClassName=org.postgresql.Driver
В этом спринте тесты на гитхабе проверяют работу с H2. Я изначально делал на Postgres, но проверки на гитхабе не проходили. Пришлось вернуть настройки для H2.

2023-02-06 11:17 UTC, valer0n3 commented on src/main/resources/application.properties
> +#spring.datasource.driverClassName=org.postgresql.Driver
В этот спринте проверки на гитхабе проходят для H2. Я изначально создавал БД на Postgres, но при загрузке на гитхаб требовалось подключение H2, поэтому пришлось оставить настройки для H2.

2023-02-06 11:18 UTC, valer0n3 commented on src/main/resources/TableCreateForPostgres.txt
> +CREATE TABLE IF NOT EXISTS users
Удалил.

2023-02-06 11:22 UTC, valer0n3 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImplementation.java
> +                .stream().map(commentMapper::mapCommentToCommentDto).collect(Collectors.toList());
Исправлено

2023-02-07 13:26 UTC, valer0n3 commented
> Задание со звездочкой: Лучше стараться максимально декомпозировать большие методы на более мелкие логические составляющие, так код будет проще читать и тестировать в дальнейшем. Предлагаю выделить общие части в сервисах и вынесли их в приватные методы. Вообще есть отличный ресурс, где можно почитать про рефакторинг кода и взять на заметку подходы по декомпозиции - [рефакторинг гуру](https://refactoring.guru/) (может не открываться без впн)

1) Изменил получение данных из БД (для Booking и Comments). Раньше SQL запросы были вложены в цикл. Теперь SQL запросы не в цикле.
2) Попытался декомпозировать; сделал как смог. Все равно вышло корявенько).

2023-02-08 09:48 UTC, AnastasiyaFomkina approved these changes
Клево получилось, молодце, что попробовал разобраться с декомпозицией и рефакторингом 👍 Оставила один комментарий, можно будет выполнить перед мержем или оставить, как есть

2023-02-08 09:48 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    private BookingStatusEnum checkIfStatusIsIncorrect(String state) {
Так как метод является частью бизнес-логики, лучше перенести его в слой сервиса. А лучше  вообще сделать статическим в классе BookingStatusEnum.

2023-02-08 09:50 UTC, AnastasiyaFomkina commented
> > Задание со звездочкой: Лучше стараться максимально декомпозировать большие методы на более мелкие логические составляющие, так код будет проще читать и тестировать в дальнейшем. Предлагаю выделить общие части в сервисах и вынесли их в приватные методы. Вообще есть отличный ресурс, где можно почитать про рефакторинг кода и взять на заметку подходы по декомпозиции - [рефакторинг гуру](https://refactoring.guru/) (может не открываться без впн)
> 
> 1. Изменил получение данных из БД (для Booking и Comments). Раньше SQL запросы были вложены в цикл. Теперь SQL запросы не в цикле.
> 2. Попытался декомпозировать; сделал как смог. Все равно вышло корявенько).

Мы только учимся, поэтому может казаться, что выглядит корявенько. Ты круто все сделал 👍 В следующих спринтах попробуем еще подекомпозировать и поразбивать код, чтобы его было проще читать и поддерживать

2023-02-09 11:46 UTC, valer0n3 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    private BookingStatusEnum checkIfStatusIsIncorrect(String state) {
Исправил.

2023-02-09 11:47 UTC, merged