#15: Sprint 15
valer0n3/java-shareit pull request #3
Opened 2023-02-13 21:02 UTC by valer0n3

2023-02-20 07:55 UTC, AnastasiyaFomkina requested changes
Привет! Хорошая работа, спасибо, что написал так много тестов 🔥 
Оставила небольшие комментарии, они достаточно общие, поищи, пожалуйста, все подобные места в коде

2023-02-20 07:55 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/request/controller/RequestController.java
> +    private static final String X_SHARER_USER_ID = "X-Sharer-User-Id";
Можно вынести этот хэдер в отдельный класс (например, `Variables`) и переиспользовать, чтобы избавиться от дублирования

2023-02-20 07:55 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImplementation.java
> +                .map(Request::getId).collect(Collectors.toList()));
Лучше бить стримы по методам, так их становится проще читать
```suggestion
                .map(Request::getId)
                .collect(Collectors.toList()));
```

2023-02-20 07:55 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImplementation.java
> +                .map(request -> mapToRequestGetAllDto(request, items)).collect(Collectors.toList());
```suggestion
                .map(request -> mapToRequestGetAllDto(request, items))
                .collect(Collectors.toList());
```
Поправь, пожалуйста, и в методах ниже

2023-02-20 07:55 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/request/storage/RequestRepository.java
> +    Page<Request> findByRequestorIdIsNot(int userId, Pageable pageable);
Можно сразу ожидать список, а не объект `Page`, так как мы не используем его методы. Проще сразу будет работать со списком, а не с оберткой пагинации
```suggestion
    List<Request> findByRequestorIdIsNot(int userId, Pageable pageable);
```
Поправь, пожалуйста, для всех репозиториев

2023-02-20 07:55 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/dto/mapper/UserMapper.java
> +    public UserPostDto mapUserToUserPostDTO(User user);
Все методы интерфейсов по дефолту `public`, поэтому лучше удалить

2023-02-20 07:55 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +    private BookingController bookingController;
Можно не инжектить мок контроллера, так как мы его никак не используем

2023-02-20 07:55 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplementationTest.java
> +    public void checkIfItemIsAvailable() {
Нужно дописать два пустых теста

2023-02-20 07:55 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/exception/ErrorHandlerTest.java
> +        Exception exception = errorHandler.incorrectValue(new IncorrectInputException("testAlert"));
Описание ошибки лучше вынести в константу и переиспользовать

2023-02-20 07:55 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/item/controller/ItemControllerTest.java
> +    private ItemController itemController;
Лишний инжект, он тоже нигде не используется

2023-02-20 07:55 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/item/dto/mapper/ItemMapperImplTest.java
> +    public void mapItemToItemForRequestDto() {
Нужно написать тест на патч

2023-02-20 07:55 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/item/dto/mapper/ItemMapperImplTest.java
> +    private ItemWithBookingDatesDto newItemWithBookingDatesDTO;
Некоторые объекты объявляются, но не используются в тестах, нужно поправить

2023-02-20 07:55 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/request/dto/mapper/RequestMapperTest.java
> +    private RequestGetAllDto newRequestGetAllDto;
Нигде не используется

2023-02-20 07:55 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/request/service/RequestServiceImplementationTest.java
> +    private RequestDto requestDto;
И этот тоже

2023-02-20 07:55 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/user/dto/mapper/UserMapperTest.java
> +        assertEquals(newUserPostDto.getName(), newUser.getName());
Некорректная проверка. Нужно проверять элемент, который получили в результате маппинга

2023-02-20 21:35 UTC, valer0n3 commented on src/main/java/ru/practicum/shareit/request/controller/RequestController.java
> +    private static final String X_SHARER_USER_ID = "X-Sharer-User-Id";
Изменения внесены.

2023-02-20 21:41 UTC, valer0n3 commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImplementation.java
> +                .map(Request::getId).collect(Collectors.toList()));
Исправлено.

2023-02-20 21:41 UTC, valer0n3 commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImplementation.java
> +                .map(request -> mapToRequestGetAllDto(request, items)).collect(Collectors.toList());
Исправлено.

2023-02-20 22:06 UTC, valer0n3 commented on src/main/java/ru/practicum/shareit/request/storage/RequestRepository.java
> +    Page<Request> findByRequestorIdIsNot(int userId, Pageable pageable);
Исправлено.

2023-02-20 22:08 UTC, valer0n3 commented on src/main/java/ru/practicum/shareit/user/dto/mapper/UserMapper.java
> +    public UserPostDto mapUserToUserPostDTO(User user);
Исправлено.

2023-02-20 22:15 UTC, valer0n3 commented on src/test/java/ru/practicum/shareit/item/dto/mapper/ItemMapperImplTest.java
> +    private ItemWithBookingDatesDto newItemWithBookingDatesDTO;
Исправлено.

2023-02-21 11:52 UTC, valer0n3 commented on src/test/java/ru/practicum/shareit/item/dto/mapper/ItemMapperImplTest.java
> +    public void mapItemToItemForRequestDto() {
Исправлено.

2023-02-21 12:06 UTC, valer0n3 commented on src/test/java/ru/practicum/shareit/item/dto/mapper/ItemMapperImplTest.java
> +    private ItemWithBookingDatesDto newItemWithBookingDatesDTO;
Исправлено.

2023-02-21 12:08 UTC, valer0n3 commented on src/test/java/ru/practicum/shareit/request/dto/mapper/RequestMapperTest.java
> +    private RequestGetAllDto newRequestGetAllDto;
Исправлено.

2023-02-21 12:09 UTC, valer0n3 commented on src/test/java/ru/practicum/shareit/request/service/RequestServiceImplementationTest.java
> +    private RequestDto requestDto;
Исправлено.

2023-02-21 12:10 UTC, valer0n3 commented on src/test/java/ru/practicum/shareit/user/dto/mapper/UserMapperTest.java
> +        assertEquals(newUserPostDto.getName(), newUser.getName());
Исправлено.

2023-02-21 17:28 UTC, AnastasiyaFomkina approved these changes

2023-03-02 14:48 UTC, merged